### ISSUE TITLE
刚运行正常，过段时间就不行了

### ISSUE THREAD

**Issue by fxecc** [LightCountry/TokenPay#15]
TokenPay创建订单失败！返回数据解析失败

**Comment by fxecc** [comment]
[15:02:31 ERR] 定时任务[TRX订单检测]执行出现错误
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.set_Connection(SqliteConnection value)
   at FreeSql.Sqlite.SqliteAdo.CreateCommand()
   at FreeSql.Internal.CommonProvider.AdoProvider.PrepareCommandAsync(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, StringBuilder logtxt, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListMrPrivateAsync[TReturn](String sql, ReadAnonymousTypeAfInfo af, ReadAnonymousTypeOtherInfo[] otherData, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select0Provider`2.InternalToListAsync[TReturn](Expression select, CancellationToken cancellationToken)
   at FreeSql.Internal.CommonProvider.Select1Provider`1.ToListAsync[TReturn](Expression`1 select, CancellationToken cancellationToken)
   at TokenPay.BgServices.OrderCheckTRXService.ExecuteAsync() in /code/TokenPay/BgServices/OrderCheckTRXService.cs:line 39
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at TokenPay.BgServices.BaseScheduledService.Execute(Object state) in /code/TokenPay/BgServices/BaseScheduledService.cs:line 35

**Comment by ninetian** [comment]
你这个看起来像SQLITE数据库崩了
一般可能是系统I/O负载高 硬盘满了 或者文件锁引起的

是不太稳，测过一段时间，不是API请求错误就是监控不到交易，请求频率太高还没容错机制
尝试过定时4小时重新启 也是会崩 监控不到交易还是存在

**Comment by fxecc** [comment]
甲骨文的 arm服务器，应该不是配置问题。  因为是用进程守护运行，目前设置的pkill -f TokenPay  4小时执行一次。
看看效果吧。 也不知道多久会出现这个情况。不行在缩短执行时间。谢谢楼上解答

**Comment by ZhangYiQiu** [comment]
建议使用x64机器，arm会出现各种奇怪的错误，新版本已经移除了arm的编译
