### ISSUE TITLE
为啥WebProxy 设置后不生效

### ISSUE THREAD

**Issue by lper** [LightCountry/TokenPay#24]
"WebProxy":"http://192.168.50.74:10809"

2024-01-11 23:25:50.361 +08:00 [WRN] Using an in-memory repository. Keys will not be persisted to storage.
2024-01-11 23:25:50.364 +08:00 [WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2024-01-11 23:26:00.454 +08:00 [ERR] 机器人连接失败！
Flurl.Http.FlurlHttpTimeoutException: Call timed out: GET https://api.telegram.org/xx/getMe
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception , Boolean , HttpResponseMessage , CancellationTokenSource , CancellationToken , CancellationTokenSource )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TokenPay.Helper.TelegramBot.GetMeAsync(String TelegramApiHost) in /code/TokenPay/Helper/TelegramBot.cs:line 43
   at Program.<>c__DisplayClass0_0.<<Main>$>b__4(IServiceProvider s) in /code/TokenPay/Program.cs:line 126

**Comment by lper** [comment]
a
