### ISSUE TITLE
独角卡对接TokenPay，订单通知报错。

### ISSUE THREAD

**Issue by zwluoqi** [LightCountry/TokenPay#37]
现象：
1.支付完成后，TokenPay的通知部分Post的接口被独角卡认为是get，导致报错：
```
#23 {main}


[12:44:29 INF] 收到响应
URL：http://xxxx.com/pay/tokenpay/notify_url
响应：<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>

[12:44:29 INF] 订单异步通知失败：Call failed with status code 405 (Method Not Allowed): GET https://xxxx.com/pay/tokenpay/notify_url
Flurl.Http.FlurlHttpException: Call failed with status code 405 (Method Not Allowed): GET https://xxxx.com/pay/tokenpay/notify_url
   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at TokenPay.BgServices.OrderNotifyService.Notify(TokenOrders order)
[12:44:29 INF] 订单: 6703d60b-d1a9-2117-000f-53014b945513，通知结果：失败
```

2.然后我去postman上面把request的body，手动post就成功了。

**Comment by zwluoqi** [comment]
[more.txt](https://github.com/user-attachments/files/17278998/more.txt)
更多日志细节。

**Comment by zwluoqi** [comment]
域名 ssl问额
